// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedItem.proto

package feedItem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FavoriteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteResponse) Reset()         { *m = FavoriteResponse{} }
func (m *FavoriteResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteResponse) ProtoMessage()    {}
func (*FavoriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{0}
}
func (m *FavoriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteResponse.Unmarshal(m, b)
}
func (m *FavoriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteResponse.Marshal(b, m, deterministic)
}
func (dst *FavoriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteResponse.Merge(dst, src)
}
func (m *FavoriteResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteResponse.Size(m)
}
func (m *FavoriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteResponse proto.InternalMessageInfo

func (m *FavoriteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FavoriteRequest struct {
	FeedItemId           int32    `protobuf:"varint,1,opt,name=feed_item_id,json=feedItemId" json:"feed_item_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteRequest) Reset()         { *m = FavoriteRequest{} }
func (m *FavoriteRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteRequest) ProtoMessage()    {}
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{1}
}
func (m *FavoriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteRequest.Unmarshal(m, b)
}
func (m *FavoriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteRequest.Marshal(b, m, deterministic)
}
func (dst *FavoriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteRequest.Merge(dst, src)
}
func (m *FavoriteRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteRequest.Size(m)
}
func (m *FavoriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteRequest proto.InternalMessageInfo

func (m *FavoriteRequest) GetFeedItemId() int32 {
	if m != nil {
		return m.FeedItemId
	}
	return 0
}

func (m *FavoriteRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FeedItemsRequest struct {
	FeedItemId           int32    `protobuf:"varint,1,opt,name=feed_item_id,json=feedItemId" json:"feed_item_id,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,3,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,4,opt,name=result_per_page,json=resultPerPage" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedItemsRequest) Reset()         { *m = FeedItemsRequest{} }
func (m *FeedItemsRequest) String() string { return proto.CompactTextString(m) }
func (*FeedItemsRequest) ProtoMessage()    {}
func (*FeedItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{2}
}
func (m *FeedItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItemsRequest.Unmarshal(m, b)
}
func (m *FeedItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItemsRequest.Marshal(b, m, deterministic)
}
func (dst *FeedItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItemsRequest.Merge(dst, src)
}
func (m *FeedItemsRequest) XXX_Size() int {
	return xxx_messageInfo_FeedItemsRequest.Size(m)
}
func (m *FeedItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItemsRequest proto.InternalMessageInfo

func (m *FeedItemsRequest) GetFeedItemId() int32 {
	if m != nil {
		return m.FeedItemId
	}
	return 0
}

func (m *FeedItemsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *FeedItemsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *FeedItemsRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type FeedItemListenRequest struct {
	FeedItemId           int32    `protobuf:"varint,1,opt,name=feed_item_id,json=feedItemId" json:"feed_item_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CurrentTime          int64    `protobuf:"varint,3,opt,name=current_time,json=currentTime" json:"current_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedItemListenRequest) Reset()         { *m = FeedItemListenRequest{} }
func (m *FeedItemListenRequest) String() string { return proto.CompactTextString(m) }
func (*FeedItemListenRequest) ProtoMessage()    {}
func (*FeedItemListenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{3}
}
func (m *FeedItemListenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItemListenRequest.Unmarshal(m, b)
}
func (m *FeedItemListenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItemListenRequest.Marshal(b, m, deterministic)
}
func (dst *FeedItemListenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItemListenRequest.Merge(dst, src)
}
func (m *FeedItemListenRequest) XXX_Size() int {
	return xxx_messageInfo_FeedItemListenRequest.Size(m)
}
func (m *FeedItemListenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItemListenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItemListenRequest proto.InternalMessageInfo

func (m *FeedItemListenRequest) GetFeedItemId() int32 {
	if m != nil {
		return m.FeedItemId
	}
	return 0
}

func (m *FeedItemListenRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FeedItemListenRequest) GetCurrentTime() int64 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

type FeedItemListenResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedItemListenResponse) Reset()         { *m = FeedItemListenResponse{} }
func (m *FeedItemListenResponse) String() string { return proto.CompactTextString(m) }
func (*FeedItemListenResponse) ProtoMessage()    {}
func (*FeedItemListenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{4}
}
func (m *FeedItemListenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItemListenResponse.Unmarshal(m, b)
}
func (m *FeedItemListenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItemListenResponse.Marshal(b, m, deterministic)
}
func (dst *FeedItemListenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItemListenResponse.Merge(dst, src)
}
func (m *FeedItemListenResponse) XXX_Size() int {
	return xxx_messageInfo_FeedItemListenResponse.Size(m)
}
func (m *FeedItemListenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItemListenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItemListenResponse proto.InternalMessageInfo

func (m *FeedItemListenResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FeedItemRequest struct {
	FeedId               int32    `protobuf:"varint,1,opt,name=feed_id,json=feedId" json:"feed_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedItemRequest) Reset()         { *m = FeedItemRequest{} }
func (m *FeedItemRequest) String() string { return proto.CompactTextString(m) }
func (*FeedItemRequest) ProtoMessage()    {}
func (*FeedItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{5}
}
func (m *FeedItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItemRequest.Unmarshal(m, b)
}
func (m *FeedItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItemRequest.Marshal(b, m, deterministic)
}
func (dst *FeedItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItemRequest.Merge(dst, src)
}
func (m *FeedItemRequest) XXX_Size() int {
	return xxx_messageInfo_FeedItemRequest.Size(m)
}
func (m *FeedItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItemRequest proto.InternalMessageInfo

func (m *FeedItemRequest) GetFeedId() int32 {
	if m != nil {
		return m.FeedId
	}
	return 0
}

type FeedItemsResponse struct {
	FeedItems            []*FeedItem `protobuf:"bytes,1,rep,name=feed_items,json=feedItems" json:"feed_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FeedItemsResponse) Reset()         { *m = FeedItemsResponse{} }
func (m *FeedItemsResponse) String() string { return proto.CompactTextString(m) }
func (*FeedItemsResponse) ProtoMessage()    {}
func (*FeedItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{6}
}
func (m *FeedItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItemsResponse.Unmarshal(m, b)
}
func (m *FeedItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItemsResponse.Marshal(b, m, deterministic)
}
func (dst *FeedItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItemsResponse.Merge(dst, src)
}
func (m *FeedItemsResponse) XXX_Size() int {
	return xxx_messageInfo_FeedItemsResponse.Size(m)
}
func (m *FeedItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItemsResponse proto.InternalMessageInfo

func (m *FeedItemsResponse) GetFeedItems() []*FeedItem {
	if m != nil {
		return m.FeedItems
	}
	return nil
}

type FeedItem struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Url         string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Image       string `protobuf:"bytes,5,opt,name=image" json:"image,omitempty"`
	// Total subscribers
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedItem) Reset()         { *m = FeedItem{} }
func (m *FeedItem) String() string { return proto.CompactTextString(m) }
func (*FeedItem) ProtoMessage()    {}
func (*FeedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedItem_d13546e755e494ab, []int{7}
}
func (m *FeedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItem.Unmarshal(m, b)
}
func (m *FeedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItem.Marshal(b, m, deterministic)
}
func (dst *FeedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItem.Merge(dst, src)
}
func (m *FeedItem) XXX_Size() int {
	return xxx_messageInfo_FeedItem.Size(m)
}
func (m *FeedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItem.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItem proto.InternalMessageInfo

func (m *FeedItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeedItem) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FeedItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FeedItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FeedItem) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *FeedItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FeedItem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*FavoriteResponse)(nil), "feedItem.FavoriteResponse")
	proto.RegisterType((*FavoriteRequest)(nil), "feedItem.FavoriteRequest")
	proto.RegisterType((*FeedItemsRequest)(nil), "feedItem.FeedItemsRequest")
	proto.RegisterType((*FeedItemListenRequest)(nil), "feedItem.FeedItemListenRequest")
	proto.RegisterType((*FeedItemListenResponse)(nil), "feedItem.FeedItemListenResponse")
	proto.RegisterType((*FeedItemRequest)(nil), "feedItem.FeedItemRequest")
	proto.RegisterType((*FeedItemsResponse)(nil), "feedItem.FeedItemsResponse")
	proto.RegisterType((*FeedItem)(nil), "feedItem.FeedItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeedItemService service

type FeedItemServiceClient interface {
	GetFeedItem(ctx context.Context, in *FeedItemRequest, opts ...grpc.CallOption) (*FeedItem, error)
	GetFeedItems(ctx context.Context, in *FeedItemsRequest, opts ...grpc.CallOption) (FeedItemService_GetFeedItemsClient, error)
	// Keep track of episode duration
	Listen(ctx context.Context, in *FeedItemListenRequest, opts ...grpc.CallOption) (*FeedItemListenResponse, error)
	// Favorite episodes (move this to own service?)
	AddFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
	RemoveFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
}

type feedItemServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedItemServiceClient(cc *grpc.ClientConn) FeedItemServiceClient {
	return &feedItemServiceClient{cc}
}

func (c *feedItemServiceClient) GetFeedItem(ctx context.Context, in *FeedItemRequest, opts ...grpc.CallOption) (*FeedItem, error) {
	out := new(FeedItem)
	err := grpc.Invoke(ctx, "/feedItem.FeedItemService/GetFeedItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedItemServiceClient) GetFeedItems(ctx context.Context, in *FeedItemsRequest, opts ...grpc.CallOption) (FeedItemService_GetFeedItemsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FeedItemService_serviceDesc.Streams[0], c.cc, "/feedItem.FeedItemService/GetFeedItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &feedItemServiceGetFeedItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeedItemService_GetFeedItemsClient interface {
	Recv() (*FeedItemsResponse, error)
	grpc.ClientStream
}

type feedItemServiceGetFeedItemsClient struct {
	grpc.ClientStream
}

func (x *feedItemServiceGetFeedItemsClient) Recv() (*FeedItemsResponse, error) {
	m := new(FeedItemsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *feedItemServiceClient) Listen(ctx context.Context, in *FeedItemListenRequest, opts ...grpc.CallOption) (*FeedItemListenResponse, error) {
	out := new(FeedItemListenResponse)
	err := grpc.Invoke(ctx, "/feedItem.FeedItemService/Listen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedItemServiceClient) AddFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	out := new(FavoriteResponse)
	err := grpc.Invoke(ctx, "/feedItem.FeedItemService/AddFavorite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedItemServiceClient) RemoveFavorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	out := new(FavoriteResponse)
	err := grpc.Invoke(ctx, "/feedItem.FeedItemService/RemoveFavorite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedItemService service

type FeedItemServiceServer interface {
	GetFeedItem(context.Context, *FeedItemRequest) (*FeedItem, error)
	GetFeedItems(*FeedItemsRequest, FeedItemService_GetFeedItemsServer) error
	// Keep track of episode duration
	Listen(context.Context, *FeedItemListenRequest) (*FeedItemListenResponse, error)
	// Favorite episodes (move this to own service?)
	AddFavorite(context.Context, *FavoriteRequest) (*FavoriteResponse, error)
	RemoveFavorite(context.Context, *FavoriteRequest) (*FavoriteResponse, error)
}

func RegisterFeedItemServiceServer(s *grpc.Server, srv FeedItemServiceServer) {
	s.RegisterService(&_FeedItemService_serviceDesc, srv)
}

func _FeedItemService_GetFeedItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedItemServiceServer).GetFeedItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedItem.FeedItemService/GetFeedItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedItemServiceServer).GetFeedItem(ctx, req.(*FeedItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedItemService_GetFeedItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FeedItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeedItemServiceServer).GetFeedItems(m, &feedItemServiceGetFeedItemsServer{stream})
}

type FeedItemService_GetFeedItemsServer interface {
	Send(*FeedItemsResponse) error
	grpc.ServerStream
}

type feedItemServiceGetFeedItemsServer struct {
	grpc.ServerStream
}

func (x *feedItemServiceGetFeedItemsServer) Send(m *FeedItemsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FeedItemService_Listen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedItemListenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedItemServiceServer).Listen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedItem.FeedItemService/Listen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedItemServiceServer).Listen(ctx, req.(*FeedItemListenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedItemService_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedItemServiceServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedItem.FeedItemService/AddFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedItemServiceServer).AddFavorite(ctx, req.(*FavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedItemService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedItemServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedItem.FeedItemService/RemoveFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedItemServiceServer).RemoveFavorite(ctx, req.(*FavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedItem.FeedItemService",
	HandlerType: (*FeedItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeedItem",
			Handler:    _FeedItemService_GetFeedItem_Handler,
		},
		{
			MethodName: "Listen",
			Handler:    _FeedItemService_Listen_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _FeedItemService_AddFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _FeedItemService_RemoveFavorite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFeedItems",
			Handler:       _FeedItemService_GetFeedItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "feedItem.proto",
}

func init() { proto.RegisterFile("feedItem.proto", fileDescriptor_feedItem_d13546e755e494ab) }

var fileDescriptor_feedItem_d13546e755e494ab = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x1b, 0x92, 0xd4, 0xe3, 0x90, 0x84, 0x15, 0xb4, 0xc1, 0x1c, 0x62, 0x7c, 0x40, 0x51,
	0x0f, 0x6e, 0x09, 0x17, 0x4e, 0x48, 0xbd, 0x04, 0x45, 0x14, 0x54, 0x99, 0xde, 0x2d, 0x27, 0x3b,
	0x8d, 0x56, 0x8a, 0x3f, 0xba, 0x1f, 0x91, 0xb8, 0xf1, 0x1f, 0xf8, 0x9f, 0xfc, 0x06, 0xb4, 0x5e,
	0xaf, 0x93, 0xd0, 0xa0, 0x22, 0xf5, 0xe6, 0x79, 0xfb, 0xde, 0xdb, 0xd9, 0x79, 0x63, 0xe8, 0xdf,
	0x21, 0xd2, 0xb9, 0xc4, 0x2c, 0x2a, 0x79, 0x21, 0x0b, 0x72, 0x62, 0x6b, 0x7f, 0xbc, 0x2a, 0x8a,
	0xd5, 0x1a, 0x2f, 0x2a, 0x7c, 0xa1, 0xee, 0x2e, 0x24, 0xcb, 0x50, 0xc8, 0x34, 0x2b, 0x0d, 0x35,
	0x3c, 0x87, 0xe1, 0x2c, 0xdd, 0x14, 0x9c, 0x49, 0x8c, 0x51, 0x94, 0x45, 0x2e, 0x90, 0x9c, 0x42,
	0x47, 0xc8, 0x54, 0x2a, 0x31, 0x72, 0x02, 0x67, 0xd2, 0x8e, 0xeb, 0x2a, 0xbc, 0x86, 0xc1, 0x96,
	0x7b, 0xaf, 0x50, 0x48, 0x12, 0x40, 0x4f, 0xdf, 0x95, 0x30, 0x89, 0x59, 0xc2, 0x68, 0x2d, 0x00,
	0x7b, 0xff, 0x9c, 0x92, 0x33, 0xe8, 0x2a, 0x81, 0x5c, 0x1f, 0x1e, 0x1b, 0x37, 0x5d, 0xce, 0x69,
	0xf8, 0xcb, 0x81, 0xe1, 0xac, 0xe6, 0x89, 0xff, 0xf7, 0x7b, 0x09, 0xed, 0x7b, 0x85, 0xfc, 0x47,
	0xe5, 0xe6, 0xc6, 0xa6, 0x20, 0x63, 0xf0, 0xca, 0x74, 0x85, 0x49, 0xae, 0xb2, 0x05, 0xf2, 0x51,
	0xcb, 0xc8, 0x34, 0xf4, 0xad, 0x42, 0xc8, 0x3b, 0x18, 0x70, 0x14, 0x6a, 0x2d, 0x93, 0x12, 0x79,
	0xa2, 0x0f, 0x46, 0xcf, 0x2a, 0xd2, 0x73, 0x03, 0xdf, 0x20, 0xbf, 0x49, 0x57, 0x18, 0x2a, 0x78,
	0x65, 0x9b, 0xba, 0x66, 0x42, 0x62, 0xfe, 0xf4, 0x97, 0x92, 0xb7, 0xd0, 0x5b, 0x2a, 0xce, 0x31,
	0x97, 0x89, 0x1e, 0x7f, 0xd5, 0x5d, 0x2b, 0xf6, 0x6a, 0xec, 0x96, 0x65, 0x18, 0x5e, 0xc2, 0xe9,
	0xdf, 0xd7, 0x3e, 0x12, 0xc6, 0x39, 0x0c, 0xac, 0xc2, 0xb6, 0x78, 0x06, 0x5d, 0xd3, 0xa2, 0xed,
	0xae, 0x53, 0x75, 0x47, 0xc3, 0x19, 0xbc, 0xd8, 0x99, 0x74, 0x6d, 0xfc, 0x1e, 0xa0, 0x79, 0x90,
	0x36, 0x6f, 0x4d, 0xbc, 0x29, 0x89, 0x9a, 0x4d, 0x6a, 0xcc, 0x5d, 0x0b, 0x89, 0xf0, 0xb7, 0x03,
	0x27, 0x16, 0x27, 0x7d, 0x38, 0x6e, 0x2e, 0x3a, 0x66, 0x94, 0x0c, 0xa1, 0xa5, 0xf8, 0xba, 0x8e,
	0x45, 0x7f, 0xea, 0xa8, 0x24, 0x93, 0x6b, 0xf3, 0x60, 0x37, 0x36, 0x05, 0x09, 0xc0, 0xa3, 0x28,
	0x96, 0x9c, 0x95, 0x92, 0x15, 0x79, 0x95, 0x82, 0x1b, 0xef, 0x42, 0x5a, 0xc7, 0x32, 0x9d, 0x50,
	0xdb, 0xe8, 0xaa, 0x82, 0x7c, 0x04, 0x77, 0xc9, 0x31, 0x95, 0x48, 0xaf, 0xe4, 0xa8, 0x13, 0x38,
	0x13, 0x6f, 0xea, 0x47, 0x66, 0xbd, 0x23, 0xbb, 0xde, 0xd1, 0xad, 0x5d, 0xef, 0x78, 0x4b, 0xd6,
	0x4a, 0x55, 0xd2, 0x5a, 0xd9, 0x7d, 0x5c, 0xd9, 0x90, 0xa7, 0x3f, 0x5b, 0xdb, 0x29, 0x7f, 0x47,
	0xbe, 0x61, 0x4b, 0x24, 0x9f, 0xc0, 0xfb, 0x8c, 0xb2, 0x19, 0xc3, 0xeb, 0x03, 0x23, 0x33, 0x79,
	0xf8, 0x07, 0xa6, 0x19, 0x1e, 0x91, 0x2f, 0xd0, 0xdb, 0xd1, 0x0b, 0xe2, 0x3f, 0x64, 0xd9, 0xdf,
	0xc1, 0x7f, 0x73, 0xf0, 0xcc, 0x04, 0x18, 0x1e, 0x5d, 0x3a, 0xe4, 0x2b, 0x74, 0xcc, 0xbe, 0x90,
	0xf1, 0x43, 0xea, 0xde, 0x02, 0xfb, 0xc1, 0xbf, 0x09, 0xd6, 0x90, 0xcc, 0xc0, 0xbb, 0xa2, 0xd4,
	0xfe, 0xe4, 0x7b, 0x6f, 0xdb, 0xff, 0xf1, 0x7d, 0xff, 0xd0, 0x51, 0xe3, 0x33, 0x87, 0x7e, 0x8c,
	0x59, 0xb1, 0xc1, 0x27, 0x5b, 0x2d, 0x3a, 0x55, 0x42, 0x1f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xc3, 0xd0, 0x80, 0xfe, 0xe4, 0x04, 0x00, 0x00,
}
