// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue.proto

package queue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddFeedItemResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeedItemResponse) Reset()         { *m = AddFeedItemResponse{} }
func (m *AddFeedItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddFeedItemResponse) ProtoMessage()    {}
func (*AddFeedItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_2094af577f7618ad, []int{0}
}
func (m *AddFeedItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeedItemResponse.Unmarshal(m, b)
}
func (m *AddFeedItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeedItemResponse.Marshal(b, m, deterministic)
}
func (dst *AddFeedItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeedItemResponse.Merge(dst, src)
}
func (m *AddFeedItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddFeedItemResponse.Size(m)
}
func (m *AddFeedItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeedItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeedItemResponse proto.InternalMessageInfo

func (m *AddFeedItemResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type RemoveFeedItemResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFeedItemResponse) Reset()         { *m = RemoveFeedItemResponse{} }
func (m *RemoveFeedItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFeedItemResponse) ProtoMessage()    {}
func (*RemoveFeedItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_2094af577f7618ad, []int{1}
}
func (m *RemoveFeedItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFeedItemResponse.Unmarshal(m, b)
}
func (m *RemoveFeedItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFeedItemResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveFeedItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFeedItemResponse.Merge(dst, src)
}
func (m *RemoveFeedItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFeedItemResponse.Size(m)
}
func (m *RemoveFeedItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFeedItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFeedItemResponse proto.InternalMessageInfo

func (m *RemoveFeedItemResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AddFeedItemRequest struct {
	FeedItemId           int32    `protobuf:"varint,1,opt,name=feed_item_id,json=feedItemId" json:"feed_item_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeedItemRequest) Reset()         { *m = AddFeedItemRequest{} }
func (m *AddFeedItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddFeedItemRequest) ProtoMessage()    {}
func (*AddFeedItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_2094af577f7618ad, []int{2}
}
func (m *AddFeedItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeedItemRequest.Unmarshal(m, b)
}
func (m *AddFeedItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeedItemRequest.Marshal(b, m, deterministic)
}
func (dst *AddFeedItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeedItemRequest.Merge(dst, src)
}
func (m *AddFeedItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddFeedItemRequest.Size(m)
}
func (m *AddFeedItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeedItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeedItemRequest proto.InternalMessageInfo

func (m *AddFeedItemRequest) GetFeedItemId() int32 {
	if m != nil {
		return m.FeedItemId
	}
	return 0
}

func (m *AddFeedItemRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type QueueRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueRequest) Reset()         { *m = QueueRequest{} }
func (m *QueueRequest) String() string { return proto.CompactTextString(m) }
func (*QueueRequest) ProtoMessage()    {}
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_2094af577f7618ad, []int{3}
}
func (m *QueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueRequest.Unmarshal(m, b)
}
func (m *QueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueRequest.Marshal(b, m, deterministic)
}
func (dst *QueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest.Merge(dst, src)
}
func (m *QueueRequest) XXX_Size() int {
	return xxx_messageInfo_QueueRequest.Size(m)
}
func (m *QueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest proto.InternalMessageInfo

// Pagination? Stream?
type QueueResponse struct {
	// TODO(fu): Describe this field.
	QueueItem            []*QueueItem `protobuf:"bytes,1,rep,name=queue_item,json=queueItem" json:"queue_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_2094af577f7618ad, []int{4}
}
func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (dst *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(dst, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetQueueItem() []*QueueItem {
	if m != nil {
		return m.QueueItem
	}
	return nil
}

type QueueItem struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FeedItem             *FeedItem            `protobuf:"bytes,2,opt,name=feed_item,json=feedItem" json:"feed_item,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueueItem) Reset()         { *m = QueueItem{} }
func (m *QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueItem) ProtoMessage()    {}
func (*QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_2094af577f7618ad, []int{5}
}
func (m *QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueItem.Unmarshal(m, b)
}
func (m *QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueItem.Marshal(b, m, deterministic)
}
func (dst *QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueItem.Merge(dst, src)
}
func (m *QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueItem.Size(m)
}
func (m *QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueItem proto.InternalMessageInfo

func (m *QueueItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueueItem) GetFeedItem() *FeedItem {
	if m != nil {
		return m.FeedItem
	}
	return nil
}

func (m *QueueItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*AddFeedItemResponse)(nil), "queue.AddFeedItemResponse")
	proto.RegisterType((*RemoveFeedItemResponse)(nil), "queue.RemoveFeedItemResponse")
	proto.RegisterType((*AddFeedItemRequest)(nil), "queue.addFeedItemRequest")
	proto.RegisterType((*QueueRequest)(nil), "queue.QueueRequest")
	proto.RegisterType((*QueueResponse)(nil), "queue.QueueResponse")
	proto.RegisterType((*QueueItem)(nil), "queue.QueueItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Queue service

type QueueClient interface {
	GetQueue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error)
	AddFeedItem(ctx context.Context, in *AddFeedItemRequest, opts ...grpc.CallOption) (*RemoveFeedItemResponse, error)
	RemoveFeedItem(ctx context.Context, in *AddFeedItemRequest, opts ...grpc.CallOption) (*RemoveFeedItemResponse, error)
}

type queueClient struct {
	cc *grpc.ClientConn
}

func NewQueueClient(cc *grpc.ClientConn) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) GetQueue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error) {
	out := new(QueueResponse)
	err := grpc.Invoke(ctx, "/queue.Queue/getQueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) AddFeedItem(ctx context.Context, in *AddFeedItemRequest, opts ...grpc.CallOption) (*RemoveFeedItemResponse, error) {
	out := new(RemoveFeedItemResponse)
	err := grpc.Invoke(ctx, "/queue.Queue/addFeedItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) RemoveFeedItem(ctx context.Context, in *AddFeedItemRequest, opts ...grpc.CallOption) (*RemoveFeedItemResponse, error) {
	out := new(RemoveFeedItemResponse)
	err := grpc.Invoke(ctx, "/queue.Queue/RemoveFeedItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Queue service

type QueueServer interface {
	GetQueue(context.Context, *QueueRequest) (*QueueResponse, error)
	AddFeedItem(context.Context, *AddFeedItemRequest) (*RemoveFeedItemResponse, error)
	RemoveFeedItem(context.Context, *AddFeedItemRequest) (*RemoveFeedItemResponse, error)
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/GetQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).GetQueue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_AddFeedItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeedItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).AddFeedItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/AddFeedItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).AddFeedItem(ctx, req.(*AddFeedItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_RemoveFeedItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeedItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).RemoveFeedItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/RemoveFeedItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).RemoveFeedItem(ctx, req.(*AddFeedItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "queue.Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getQueue",
			Handler:    _Queue_GetQueue_Handler,
		},
		{
			MethodName: "addFeedItem",
			Handler:    _Queue_AddFeedItem_Handler,
		},
		{
			MethodName: "RemoveFeedItem",
			Handler:    _Queue_RemoveFeedItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queue.proto",
}

func init() { proto.RegisterFile("queue.proto", fileDescriptor_queue_2094af577f7618ad) }

var fileDescriptor_queue_2094af577f7618ad = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x96, 0xd6, 0x66, 0x52, 0x83, 0x4c, 0xa5, 0xd6, 0x80, 0x58, 0xf6, 0xd4, 0x8b,
	0x89, 0xd4, 0x83, 0x78, 0xb3, 0x17, 0x21, 0x20, 0x88, 0xc1, 0x7b, 0x49, 0xdd, 0x69, 0x09, 0x18,
	0xd3, 0x76, 0x27, 0xbe, 0x82, 0xcf, 0xe8, 0xdb, 0x48, 0x76, 0x37, 0xa1, 0x45, 0x0f, 0x82, 0xb7,
	0x9d, 0xbf, 0xfb, 0xfb, 0xe6, 0x03, 0x6f, 0x5b, 0x52, 0x49, 0xe1, 0x66, 0x57, 0x70, 0x81, 0x5d,
	0x1d, 0x04, 0x97, 0xeb, 0xa2, 0x58, 0xbf, 0x51, 0xa4, 0x93, 0xcb, 0x72, 0x15, 0x71, 0x96, 0x93,
	0xe2, 0x34, 0xdf, 0x98, 0xbe, 0xc0, 0x5f, 0x11, 0xc9, 0x98, 0x29, 0x37, 0xb1, 0xb8, 0x82, 0xe1,
	0x5c, 0xca, 0x07, 0x9b, 0x4c, 0x48, 0x6d, 0x8a, 0x77, 0x45, 0x38, 0x82, 0x9e, 0xe2, 0x94, 0x4b,
	0x35, 0x76, 0x26, 0xce, 0xb4, 0x9b, 0xd8, 0x48, 0x5c, 0xc3, 0x28, 0xa1, 0xbc, 0xf8, 0xa0, 0x3f,
	0x4f, 0x3c, 0x01, 0xa6, 0xfb, 0x1f, 0x6c, 0x4b, 0x52, 0x8c, 0x13, 0x18, 0x54, 0x20, 0x8b, 0x8c,
	0x29, 0x5f, 0x64, 0xd2, 0xce, 0x40, 0x0d, 0x17, 0x4b, 0x3c, 0x83, 0xa3, 0x52, 0xd1, 0xae, 0x2a,
	0xb6, 0xcd, 0xc2, 0x2a, 0x8c, 0xa5, 0xf0, 0x61, 0xf0, 0x5c, 0x69, 0xb5, 0xab, 0xc4, 0x3d, 0x1c,
	0xdb, 0xd8, 0x92, 0x44, 0x00, 0xfa, 0x18, 0x7a, 0xf9, 0xd8, 0x99, 0x74, 0xa6, 0xde, 0xec, 0x24,
	0x34, 0xc7, 0xd2, 0x9d, 0x1a, 0xc4, 0xdd, 0xd6, 0x4f, 0xf1, 0xe9, 0x80, 0xdb, 0x14, 0xd0, 0x87,
	0x76, 0x03, 0xd4, 0xce, 0x24, 0x46, 0xe0, 0x36, 0xa8, 0x1a, 0xc5, 0x9b, 0x61, 0xd8, 0x5c, 0xb1,
	0x11, 0xd6, 0xaf, 0x53, 0x78, 0x07, 0xf0, 0xba, 0xa3, 0x94, 0x49, 0x2e, 0x52, 0x1e, 0x77, 0xf4,
	0x44, 0x10, 0x1a, 0x63, 0xc2, 0xda, 0x98, 0xf0, 0xa5, 0x36, 0x26, 0x71, 0x6d, 0xf7, 0x9c, 0x67,
	0x5f, 0x0e, 0x74, 0x35, 0x09, 0xde, 0x42, 0x7f, 0x4d, 0x6c, 0xde, 0xc3, 0x7d, 0x78, 0x2b, 0x3b,
	0x38, 0x3d, 0x4c, 0x1a, 0xed, 0xa2, 0x85, 0x31, 0x78, 0x7b, 0xf7, 0xc6, 0x73, 0xdb, 0xf6, 0xd3,
	0x83, 0xe0, 0xc2, 0x96, 0x7e, 0x37, 0x54, 0xb4, 0xf0, 0x11, 0xfc, 0xc3, 0xda, 0x7f, 0xb6, 0x2d,
	0x7b, 0x5a, 0xfa, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x71, 0x60, 0x49, 0xb7, 0x02,
	0x00, 0x00,
}
